---
apiVersion: v2
description: A Helm chart for deploying GeoMapFish on Kubernetes
name: geomapfish
version: 0.1.0
home: http://geomapfish.org/
sources:
  - https://github.com/camptocamp/c2cgeoportal
icon: http://geomapfish.org/images/brand/logo.png
dependencies:
  - name: common
    repository: https://camptocamp.github.io/helm-common
    version: 0.7.1
