nameOverride: ''
fullnameOverride: ''

imagePullSecrets: []
replicaCount: 1

entrypoint: /

env: {}
annotations: {}

image: &image
  repository: camptocamp/geomapfishapp-geoportal
  tag: latest
  sha:
  pullPolicy: IfNotPresent

config:
  image:
    repository: camptocamp/<project>-config
    tag: latest
    sha:
  env: {}
  resources: {}

mutualize:
  repository: camptocamp/to-fill
  branch: master
  key: to-fill
  # Should be https://config.mutualize(-int)?.camptocamp.com
  configUrl: to-fill
  tccService: service.namespace.svc.cluster.local
  configs: {}
  #  test-print:
  #    host: demo.camptocamp.com
  #    dir: print/print-apps/test
  #    env:
  #      TEST: test
  #  test-tilecloudchain:
  #    host: demo.camptocamp.com
  #    dir: tilegeneration
  #    tilecloudchain: true
  #    env:
  #      TEST: test

postgresql:
  schema: main
  staticSchema: main_static
  statementTimeout: 30000 # milliseconds

redis:
  host: ''
  port: 6379
  db: 0
  servicename: mymaster
  timeout: 10

sentry:
  hostname: o330647.ingest.sentry.io
  key: sentry-key
  project: sentry-project

probe:
  liveness:
    healthCheckLevel: 0
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 30
  readiness:
    healthCheckLevel: 0
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 30

alembic:
  enabled: true
  image: *image
  serviceName: alembic
  env: {}
  annotations: {}
  resources: {}

busybox:
  image:
    repository: busybox
    tag: latest
  serviceName: busybox
  env: {}
  annotations: {}
  resources: {}

statsd:
  serviceName: statsd
  enabled: true
  image:
    repository: ghcr.io/camptocamp/c2cwsgiutils
    tag: latest
    sha:
  env: {}
  annotations: {}
  resources: {}

tools:
  serviceName: tools
  enabled: true
  image:
    repository: camptocamp/geomapfish-tools
    tag: latest
    sha:
  env: {}
  annotations: {}
  resources: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: default

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  runAsNonRoot: true
  runAsUser: 33 # www-data
  # capabilities:
  #   drop:
  #   - ALL

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

prometheus: true
