geoportal:
  config: &config
    image: &config-image
      repository: camptocamp/<project>-config
      tag: latest

mapserver:
  config:
    <<: *config
    enabled: true
    folder: /etc/mapserver

qgisserver:
  config:
    <<: *config
    enabled: true
    folder: /etc/qgisserver

mutualize:
  repository: camptocamp/to-fill
  branch: master
  key: to-fill
  # Should be https://config.mutualize(-int)?.camptocamp.com
  configUrl: to-fill
  configs: {}
  #  test-print:
  #    dir: print/print-apps/test
  #    env:
  #      TEST: test
  #  test-tilecloudchain:
  #    tilecloudchain: true
  #    dir: tilegeneration
  #    env:
  #      TEST: test
  #    hosts:
  #      - name: test
  #        host: test.tiles.example.com
  #        tls:
  #          secretName: test-tile-tls
  tiles:
    service:
      name: service name to define
      port: 8080
    ingress:
      annotations: []
      paths:
        []
        # - /

postgresql:
  schema: main
  staticSchema: main_static
  statementTimeout: 30000 # milliseconds

redis:
  host: ''
  port: 6379
  db: 0
  servicename: mymaster
  timeout: 10

sentry:
  hostname: o330647.ingest.sentry.io
  key: sentry-key
  project: sentry-project

statsd:
  url: monitoring-statsd:9125

entrypoint: /
