geoportal:
  config: &config
    image: &config-image
      repository: camptocamp/<project>-config
      tag: latest

  dbstats:
    # Should be on geoportal
    serviceName: dbstats

mapserver:
  config:
    <<: *config
    enabled: true
    folder: /etc/mapserver

qgisserver:
  config:
    <<: *config
    enabled: true
    folder: /etc/qgisserver

gunicorn:
  nbThreads: 10
  nbProcesses: 2
  maxRequests: 2000
  maxRequestsJitter: 200
  timeout: 30

postgresql:
  schema: main
  staticSchema: main_static
  statementTimeout: 30000 # milliseconds

redis:
  host: ''
  port: 6379
  db: 0
  servicename: mymaster
  timeout: 10

sentry:
  hostname: o330647.ingest.sentry.io
  key: sentry-key
  project: sentry-project

statsd:
  url: monitoring-statsd:9125

ingress:
  hosts:
    - name: main
      host: example.com

entrypoint: /
