{{- if .Values.geoportal.alembic.enabled }}
apiVersion: apps/v1
kind: Deployment
{{- $service := "alembic" }}
metadata:
  name: {{ template "c2cgeoportal.fullname" . }}-{{ $service }}
  labels:
    app: {{ template "c2cgeoportal.fullname" . }}
    chart: {{ template "c2cgeoportal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: {{ $service }}
  {{- if .Values.openshift }}
  annotations:
    image.openshift.io/triggers: |
      [
        {{ template "c2cgeoportal.trigger" (dict "image" "geoportal" "tag" .Values.image.tag "initContainer" "alembic" "root" . ) }}
      ]
  {{- end }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "c2cgeoportal.fullname" . }}
      release: {{ .Release.Name }}
      service: {{ $service }}
  template:
    metadata:
      labels:
        app: {{ template "c2cgeoportal.fullname" . }}
        release: {{ .Release.Name }}
        service: {{ $service }}
    spec:
      {{- include "commonPodConfig" (dict "service" .Values.geoportal "affinitySelector" (dict "release" .Release.Name "service" $service) "root" .) | indent 6 }}
      initContainers:
      - name: alembic
        {{- if .Values.openshift }}
        image: " "
        {{- else }}
        {{-   if .Values.geoportal.image }}
        image: "{{ .Values.geoportal.image }}"
        {{-   else }}
        image: "{{ .Values.image.repositoryPrefix }}-geoportal:{{ .Values.image.tag }}"
        {{-   end }}
        {{- end }}
        imagePullPolicy: {{ .Values.openshift | ternary "IfNotPresent" .Values.image.pullPolicy }}
        # Set the command to disable the entrypoint that evaluate templates.
        args:
        {{- if .Values.geoportal.alembic.mainStatic }}
          - bash
          - -c
          - alembic --name=main upgrade head && alembic --name=static upgrade head
        {{- else }}
          - alembic
          - --name=static
          - upgrade
          - head
        {{- end }}
        env:
          # Config env
          {{- include "c2cgeoportal.configEnv" . | indent 10}}
          # Geoportal env
          {{- range $name, $value := .Values.geoportal.env }}
          - name: {{ $name | quote }}
            value: {{ $value | quote }}
          {{- end }}
        {{- include "common.containerConfig" (dict "service" .Values.geoportal.alembic "root" .) | indent 8 }}
      containers:
      - name: sleep
        image: busybox:latest
        args:
          - sleep
          - infinity
        {{- include "common.containerConfig" (dict "service" .Values.geoportal.busybox "root" .) | indent 8 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
{{- end }}
