{{- if .Values.alembic.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.alembic ) }}
  {{- include "common.metadata" ( dict "root" . "service" .Values.alembic ) | nindent 2 }}
spec:
  activeDeadlineSeconds: 600
  template:
    metadata: {{- include "common.podMetadata" ( dict "root" . "service" .Values.alembic ) | nindent 6 }}
    spec: {{- include "common.podConfig" ( dict "root" . "service" .Values.alembic ) | nindent 6 }}
      restartPolicy: Never
      containers:
        - name: alembic
          {{- include "common.containerConfig" ( dict "root" . "container" .Values.alembic ) | nindent 10 }}
          args:
            - bash
            - -c
          {{- if .Values.alembic.mainStatic }}
            - alembic --name=main upgrade head && alembic --name=static upgrade head
          {{- else }}
            - alembic --name=static upgrade head
          {{- end }}
{{- end }}
