apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" ( dict "serviceName" "env" ) ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" ( dict "serviceName" "env" ) ) | nindent 4 }}
data:
  RELEASE_NAME: {{ .Release.Name }}
  GEOPORTAL_IMAGE_TAG: {{ .Values.image.tag | quote }}
  ALEMBIC_IMAGE_TAG: {{ .Values.alembic.image.tag | quote }}
  TOOLS_IMAGE_TAG: {{ .Values.tools.image.tag | quote }}
  CONFIG_IMAGE_TAG: {{ .Values.config.image.tag | quote }}
  STATD_IMAGE_TAG: {{ .Values.statsd.image.tag | quote }}
  BUSYBOX_IMAGE_TAG: {{ .Values.busybox.image.tag | quote }}
