apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values ) }}-env
  labels: {{ include "common.labels" ( dict "root" . "service" .Values ) | nindent 4 }}
data:
  CHART_NAME: {{ .Chart.Name }}
  RELEASE_NAME: {{ .Release.Name }}
  RELEASE_NAMESPACE: {{ .Release.Namespace }}
  GUNICORN_PARAMS: >-
    --bind=:8080
    --worker-class=gthread
    --threads={{ .Values.gunicorn.nbThreads }}
    --workers={{ .Values.gunicorn.nbProcesses }}
    {{- if gt .Values.gunicorn.nbProcesses 1.0 }}
    --max-requests=2000
    --max-requests-jitter=200
    {{- end }}
    --timeout={{ .Values.gunicorn.timeout }}
    {{- if .Values.statsd.enabled }}
    --statsd-host={{ .Values.statsd.url }}
    --statsd-prefix={{ .service }}.{{ .Release.Name }}
    {{- end }}
    {{- if .Values.gunicorn.config }}
    --config={{ .Values.gunicorn.config }}
    {{- end }}
    --worker-tmp-dir=/dev/shm
  SENTRY_URL: https://{{ .Values.sentry.key }}@{{ .Values.sentry.hostname }}/{{ .Values.sentry.project }}
  TILECLOUDCHAIN_INTERNAL_URL: http://{{ include "common.fullname" ( dict "root" . "service" .Values ) }}-tilecloudchain/
  GEOPORTAL_INTERNAL_URL: http://{{ include "common.fullname" ( dict "root" . "service" .Values ) }}-geoportal/
  MAPSERVER_URL: http://{{ include "common.fullname" ( dict "root" . "service" .Values ) }}-mapserver/
  QGISSERVER_URL: http://{{ include "common.fullname" ( dict "root" . "service" .Values ) }}-qgisserver/
  GEOPORTAL_INTERNAL_HOST: {{ include "common.fullname" ( dict "root" . "service" .Values ) }}-geoportal
  TILECLOUDCHAIN_INTERNAL_HOST: {{ include "common.fullname" ( dict "root" . "service" .Values ) }}-tilecloudchain
  VISIBLE_WEB_HOST: {{ (index .Values.geoportal.ingress.hosts 0).host }}
  VISIBLE_ENTRY_POINT: {{ .Values.entrypoint }}
  VISIBLE_WEB_HOST_RE_ESCAPED: {{ replace "." "\\." (index .Values.geoportal.ingress.hosts 0).host | quote }}
  VISIBLE_ENTRY_POINT_RE_ESCAPED: {{ replace "." "\\." .Values.entrypoint | quote }}

  PGSCHEMA: {{ .Values.postgresql.schema | quote }}
  PGSCHEMA_STATIC: {{ .Values.postgresql.staticSchema | quote }}
  PGOPTIONS: "-c statement_timeout={{ .Values.postgresql.statementTimeout}}"

  REDIS_SENTINELS: "{{ .Values.redis.host }}:{{ .Values.redis.port }}"
  REDIS_DB: {{ .Values.redis.db | quote }}
  REDIS_SERVICENAME: {{ .Values.redis.servicename | quote }}
  REDIS_TIMEOUT: {{ .Values.redis.timeout | quote }}
  REDIS_GEOPORTAL_BROADCAST_PREFIX:  broadcast_geoportal_{{ .Values.redis.db }}

  MAPSERVER_DATA_SUBSELECT: >
    SELECT ST_Collect(ra.area)
    FROM {{ .Values.postgresql.schema }}.restrictionarea AS ra,
    {{ .Values.postgresql.schema }}.role_restrictionarea AS rra,
    {{ .Values.postgresql.schema }}.layer_restrictionarea AS lra,
    {{ .Values.postgresql.schema }}.treeitem AS la
    WHERE rra.role_id in (%role_ids%) AND rra.restrictionarea_id = ra.id
    AND lra.restrictionarea_id = ra.id AND lra.layer_id = la.id AND la.name =
  MAPSERVER_DATA_NOAREA_SUBSELECT: >
    SELECT rra.role_id
    FROM {{ .Values.postgresql.schema }}.restrictionarea AS ra,
    {{ .Values.postgresql.schema }}.role_restrictionarea AS rra,
    {{ .Values.postgresql.schema }}.layer_restrictionarea AS lra,
    {{ .Values.postgresql.schema }}.treeitem AS la
    WHERE rra.restrictionarea_id = ra.id AND lra.restrictionarea_id = ra.id
    AND lra.layer_id = la.id AND la.name =
  MAPSERVER_JOIN_TABLES: >
    {{ .Values.postgresql.schema }}.restrictionarea AS ra,
    {{ .Values.postgresql.schema }}.role_restrictionarea AS rra,
    {{ .Values.postgresql.schema }}.layer_restrictionarea AS lra,
    {{ .Values.postgresql.schema }}.treeitem AS la
  MAPSERVER_JOIN_WHERE: >
    rra.role_id in (%role_ids%) AND rra.restrictionarea_id = ra.id AND
    lra.restrictionarea_id = ra.id AND lra.layer_id = la.id AND la.name =
  GEOPORTAL_BROADCAST_PREFIX: broadcast_geoportal_{{ .Values.redis.db }}

  GEOPORTAL_CLIENT_RELEASE: {{ .Values.geoportal.image.tag | quote }}
  ALEMBIC_CLIENT_RELEASE: {{ .Values.geoportal.alembic.image.tag | quote }}
  DBSTATS_CLIENT_RELEASE: {{ .Values.geoportal.dbstats.image.tag | quote }}
