{{- if and .Values.c2c.statsd.enabled .Values.c2c.statsd.dbstats.enabled}}
apiVersion: batch/v1beta1
kind: CronJob
{{- $service := "dbstats" }}
metadata:
  name: {{ template "c2cgeoportal.fullname" . }}-{{ $service }}
  labels:
    app: {{ template "c2cgeoportal.fullname" . }}
    chart: {{ template "c2cgeoportal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: {{ $service }}
spec:
  schedule: "{{ mod (regexReplaceAll "[a-f]+" (printf "%s-%s" .Release.Namespace .Release.Name | sha256sum) "" | trunc 5) 60 }} * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:  # POD level
        metadata:
          labels:
            app: {{ template "c2cgeoportal.fullname" . }}
            release: {{ .Release.Name }}
            service: {{ $service }}
        spec:
          {{- include "commonPodConfig" (dict "service" .Values.geoportal "affinitySelector" (dict "release" .Release.Name "service" $service) "root" .) | indent 10 }}
          containers:
            - name: dbstats
              image: ghcr.io/camptocamp/c2cwsgiutils:4
              imagePullPolicy: Always
              env:
              {{- range $name, $value := .Values.c2c.statsd.dbstats.env }}
                - name: {{ $name | quote }}
                  value: {{ $value | quote }}
              {{- end }}
                {{- if .Values.c2c.sentry.enabled }}
                - name: SENTRY_URL
                  value: https://{{ .Values.c2c.sentry.key }}@{{ .Values.c2c.sentry.hostname }}/{{ .Values.c2c.sentry.project }}
                - name: SENTRY_CLIENT_RELEASE
                  value: {{ .Values.image.tag | quote }}
                - name: SENTRY_CLIENT_ENVIRONMENT
                  value: {{ .Release.Name }}
                - name: SENTRY_TAG_SERVICE
                  value: dbstats
                {{- end }}
                - name: PGHOST
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.postgresql.secret }}
                      key: hostnameSlave
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.postgresql.secret }}
                      key: database
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.postgresql.secret }}
                      key: username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.postgresql.secret }}
                      key: password
                - name: STATSD_USE_TAGS
                  value: "1"
                - name: STATSD_TAG_CHART
                  value: {{ .Chart.Name }}
                - name: STATSD_TAG_RELEASE
                  value: {{ .Release.Name }}
                {{- if .Values.c2c.statsd.dbstats.prometheus }}
                - name: STATSD_TAG_NAMESPACE
                  value: {{ .Release.Namespace }}
                {{- end }}
              args:
                - bash
                - -ce
                - |
                  {{- if .Values.c2c.statsd.dbstats.prometheus }}
                  TARGET="--prometheus_instance={{ .Release.Namespace }}-{{ template "c2cgeoportal.fullname" . }} --prometheus_url={{ .Values.c2c.statsd.dbstats.prometheus }}"
                  {{- else }}
                  TARGET="--statsd_address={{ .Values.c2c.statsd.url }} --statsd_prefix=dbstats"
                  {{- end }}
                  export STATSD_TAG_DB=$(PGDATABASE)
                  c2cwsgiutils-stats-db \
                    --db=postgresql://$(PGUSER):$(PGPASSWORD)@$(PGHOST):5432/$(PGDATABASE) \
                  {{- if .Values.postgresql.schema }}
                    --schema={{ .Values.postgresql.schema }} \
                  {{- end }}
                    --schema={{ .Values.postgresql.staticSchema }} \
                    {{- range .Values.c2c.statsd.dbstats.extraSchemas }}
                    --schema={{ . }} \
                    {{- end }}
                    ${TARGET}
                  {{- range .Values.c2c.statsd.dbstats.extraDBs  }}
                  {{-   if $.Values.c2c.statsd.dbstats.prometheus }}
                  TARGET="--prometheus_instance={{ $.Release.Namespace }}-{{ template "c2cgeoportal.fullname" $ }}-{{ .database }} --prometheus_url={{ $.Values.c2c.statsd.dbstats.prometheus }}"
                  {{-   else }}
                  TARGET="--statsd_address={{ $.Values.c2c.statsd.url }} --statsd_prefix=dbstats.{{ .database }}"
                  {{-   end }}
                  export STATSD_TAG_DB="{{ .database }}"
                  c2cwsgiutils-stats-db \
                    --db=postgresql://{{ .user | default "$(PGUSER)" }}:{{ .password | default "$(PGPASSWORD)" }}@{{ .host | default "$(PGHOST)" }}:5432/{{ .database }} \
                    --verbosity WARNING \
                    {{- if .schemas }}
                    {{-   range .schemas }}
                    --schema={{ . }} \
                    {{-   end }}
                    {{- else }}
                    --schema=public \
                    {{- end }}
                    ${TARGET}
                  {{- end }}
              {{- include "common.containerConfig" (dict "service" .Values.c2c.statsd.dbstats "root" .) | indent 14 }}
          restartPolicy: Never
{{- end }}
