{{- if .Values.imagePullSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "c2cgeoportal.fullname" . }}-dockerhubcred
  labels:
    app: {{ template "c2cgeoportal.fullname" . }}
    chart: {{ template "c2cgeoportal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{{ include "dockercred" . | b64enc }}"
{{- end -}}
