{{- if .Values.geoportal.prometheus }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "c2cgeoportal.fullname" . }}-geoportal-prometheus
  labels:
    app: {{ template "c2cgeoportal.fullname" . }}
    chart: {{ template "c2cgeoportal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: geoportal-prometheus
    prometheus: "true"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: prometheus
  selector:
    app: {{ template "c2cgeoportal.fullname" . }}
    release: {{ .Release.Name }}
    service: geoportal
{{- end }}
