{{- if .Values.mutualize.enabled }}
{{- range $name, $value := .Values.mutualize.configs }}
---
apiVersion: camptocamp.com/v4
kind: GitHubWebhook{{ $.Values.mutualize.environment | title }}
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values.mutualize.webhook "serviceName" $name ) }}
  {{- include "common.metadata" ( dict "root" $ "service" $.Values.mutualize.webhook "serviceName" $name) | nindent 2 }}
spec:
  repository: {{ $.Values.mutualize.repository }}
  url: {{ $.Values.mutualize.configUrl }}/1/refresh/{{ $name }}
  contentType: json
  {{- with $.Values.mutualize.secret }}
  secret: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
