{{- if .Values.mapserver.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "c2cgeoportal.fullname" . }}-mapserver
  labels:
    app: {{ template "c2cgeoportal.fullname" . }}
    chart: {{ template "c2cgeoportal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: mapserver
    prometheus: "true"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 9117
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  selector:
    app: {{ template "c2cgeoportal.fullname" . }}
    release: {{ .Release.Name }}
    service: mapserver
{{- end -}}
