{{- if .Values.mutualize.enabled }}
{{- if .Values.mutualize.rbac }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.mutualize ) }}
  {{- include "common.metadata" ( dict "root" . "service" .Values.mutualize ) | nindent 2 }}
subjects:
{{- range .Values.mutualize.rbacGroups }}
- kind: Group
  name: {{ . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
roleRef:
  kind: Role
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.mutualize ) }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
