---
{{- if .Values.mutualize.redirect.hosts }}
apiVersion: camptocamp.com/v2
kind: SharedConfigSource
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" ( dict "serviceName" "redirect" )) }}-hosts
  labels: {{ include "common.labels" ( dict "root" $ "service" ( dict "serviceName" "redirect-hosts" ) ) | nindent 4 }}
    mutualize-redirect-hosts: 'true'
spec:
  name: {{ include "common.fullname" ( dict "root" $ "service" ( dict "serviceName" "redirect" )) }}-hosts
  environment: {{ $.Values.mutualize.environment }}
  content:
{{- range $host := .Values.mutualize.redirect.hosts }}
   {{ $host }}: {{ $host }}
{{- end }}
{{- end }}
