{{- range $name, $config := .Values.mutualize.configs }}
{{- if $config.tilecloudchain }}
{{- range $host := $config.hosts }}
---
apiVersion: camptocamp.com/v2
kind: SharedConfigSource
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" ( dict "serviceName" $name )) }}-hosts-{{ $host.name }}
  labels: {{ include "common.labels" ( dict "root" $ "service" ( dict "serviceName" $name ) ) | nindent 4 }}
    mutualize-tilecloudchain-hosts: 'true'
spec:
  name: {{ $name }}-{{ $host.name }}
  environment: {{ $.Values.mutualize.environment }}
  content:
    {{ $host.host }}: /etc/tilecloudchain-configs/{{ $name }}/config.yaml
{{- end }}
{{- end }}
{{- end }}
