{{- range $name, $config := .Values.mutualize.configs }}
{{- if $config.tilecloudchain }}
{{- range $host := $config.hosts }}
---
apiVersion: camptocamp.com/v3
kind: SharedConfigSource{{ $.Values.mutualize.environment | title }}
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values.mutualize.sharedConfig "serviceName" $name ) }}-hosts-{{ $host.name }}
  {{- include "common.metadata" ( dict "root" $ "service" $.Values.mutualize.sharedConfig "serviceName" $name ) | nindent 2 }}
    mutualize-tilecloudchain-hosts: 'true'
spec:
  name: {{ $name }}-{{ $host.name }}
  content:
    {{ $host.host }}: /etc/tilecloudchain-configs/{{ $name }}/config.yaml
{{- end }}
{{- end }}
{{- end }}
