{{- range $name, $value := .Values.mutualize.configs }}
---
apiVersion: camptocamp.com/v2
kind: SharedConfigSource
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values.mutualize.sharedConfig "serviceName" $name ) }}
  {{- include "common.metadata" ( dict "root" $ "service" $.Values.mutualize.sharedConfig "serviceName" $name  ) | nindent 2 }}
    mutualize-sharedconfig: 'true'
spec:
  name: {{ $name }}
  environment: {{ $.Values.mutualize.environment }}
  content:
      type: git
      repo: git@github.com:{{ $.Values.mutualize.repository }}.git
      branch: {{ $.Values.mutualize.branch }}
      sub_dir: {{ .dir }}
      tags:
      {{- if .tilecloudchain }}
        - tilecloudchain
      {{- else }}
        - print
      {{- end }}
      template_engines:
        - type: shell
          environment_variables: true
          {{- with .env }}
          data:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
