{{- if .Values.mutualize.enabled }}
{{- if .Values.mutualize.rbac }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.mutualize ) }}
  {{- include "common.metadata" ( dict "root" . "service" .Values.mutualize ) | nindent 2 }}
rules:
- apiGroups:
    - camptocamp.com
  resources:
    - sharedconfigconfigs{{ $.Values.mutualize.environment | lower }}
    - sharedconfigsources{{ $.Values.mutualize.environment | lower }}
    - githubwebhooks{{ $.Values.mutualize.environment | lower }}
  verbs:
    - get
    - watch
    - list
    - create
    - update
    - patch
    - delete
{{- end }}
{{- end }}
