# For backend pod (that should only be access from the geoportal pod)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values ) | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      backend: backend
  policyTypes:
    - Ingress
  ingress:
    # For Prometheus
    - ports:
        - port: prometheus
          protocol: TCP
    # For geoportal
    - from:
        - podSelector:
            matchLabels: {{- include "common.selectorLabels" ( dict "root" . "service" .Values ) | nindent 14 }}
      {{- with .Values.networkPolicy.ports }}
      ports:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .Values.tools.enabled }}
---
# No ingress traffic for tools
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.tools ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.tools ) | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "common.selectorLabels" ( dict "root" . "service" .Values.tools ) | nindent 6 }}
  policyTypes:
    - Ingress
{{- end }}
