{{- if .Values.podMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" .Values ) }}
  labels: {{ include "common.labels" ( dict "root" $ "service" .Values ) | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "common.selectorLabels" ( dict "root" $ "service" .Values ) | nindent 6 }}
  {{- with .Values.podMonitor.endpoint }}
  podMetricsEndpoints:
    - {{ . | toYaml | nindent 6 }}
  {{- end }}
{{- end }}
