{{- if .Values.sharedConfigManager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "c2cgeoportal.fullname" . }}-shared-config
  labels:
    app: {{ template "c2cgeoportal.fullname" . }}
    chart: {{ template "c2cgeoportal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: shared-config
  {{- if .Values.openshift }}
  annotations:
    image.openshift.io/triggers: |
      [
        {{ template "c2cgeoportal.trigger" (dict "image" "sharedconfigmanager" "tag" .Values.sharedConfigManager.image.tag "container" "shared-config" "root" . ) }}
      ]
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "c2cgeoportal.fullname" . }}
      release: {{ .Release.Name }}
      service: shared-config
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "c2cgeoportal.fullname" . }}
        release: {{ .Release.Name }}
        service: shared-config
    spec:
      {{- include "commonPodConfig" (dict "service" .Values.sharedConfigManager "root" .) | indent 6 }}
      containers:
        - name: shared-config
          {{- template "c2cgeoportal.sharedConfig" (dict "service" "config_api" "root" .) }}
            - name: API_MASTER
              value: "1"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /scm/c2c/health_check
              port: http
            initialDelaySeconds: 10
          securityContext:
            runAsNonRoot: true
            {{- if not .Values.openshift }}
            runAsUser: 33  # www-data
            {{- end }}
          volumeMounts:
            - name: ssh-key
              readOnly: true
              mountPath: "/var/www/.ssh2"
          {{- include "common.containerConfig" (dict "service" .Values.sharedConfigManager "root" .) | indent 10 }}
      volumes:
        - name: ssh-key
          secret:
            secretName: secrets-ssh-key
            defaultMode: 0440
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
{{- end }}
