{{- if .Values.mutualize.tccService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" ( dict "serviceName" "tiles" ) ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" ( dict "serviceName" "tiles" ) ) | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.mutualize.tccService }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
{{- end }}
