
{{- if .Values.tools.enabled }}
{{- $fullname := include "c2cgeoportal.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-tools
  labels:
    app: {{ template "c2cgeoportal.fullname" . }}
    chart: {{ template "c2cgeoportal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: tools
  {{- if .Values.openshift }}
  annotations:
    image.openshift.io/triggers: |
      [
        {{ template "c2cgeoportal.trigger" (dict "image" "tools" "tag" .Values.image.tag "container" "tools" "root" . ) }}
      ]
  {{- end }}
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "c2cgeoportal.fullname" . }}
      release: {{ .Release.Name }}
      service: tools
  template:
    metadata:
      labels:
        app: {{ template "c2cgeoportal.fullname" . }}
        release: {{ .Release.Name }}
        service: tools
    spec:
      {{- include "commonPodConfig" (dict "service" .Values.tools "root" .) | indent 6 }}
      containers:
        - name: tools
          {{- if .Values.openshift }}
          image: " "
          {{- else }}
          {{-   if .Values.tools.image }}
          image: "{{ .Values.tools.image }}"
          {{-   else }}
          image: "{{ .Values.image.repositoryPrefix }}-tools:{{ .Values.image.tag }}"
          {{-   end }}
          {{- end }}
          imagePullPolicy: {{ .Values.openshift | ternary "IfNotPresent" .Values.image.pullPolicy }}
          args:
           - sleep
           - infinity
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            # Config env
            {{- include "c2cgeoportal.configEnv" . | indent 12}}
          {{- include "common.containerConfig" (dict "service" .Values.tools "root" .) | indent 10 }}
          securityContext:
            runAsNonRoot: true
            {{- if not .Values.openshift }}
            runAsUser: 33  # www-data
            {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
{{- end }}
